#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - gnupg2
  - ca-certificates
  - lsb-release
  - software-properties-common
  - apt-transport-https
  - git
  - zsh
  - ibus
  - snapd

runcmd:
  # VS Code
  - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
  - echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
  - apt update
  - apt install -y code

  # Postman via Snap
  - snap install postman

  # Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker ubuntu
  - rm get-docker.sh

  # Docker Compose
  - mkdir -p /home/ubuntu/.docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /home/ubuntu/.docker/cli-plugins/docker-compose
  - chmod +x /home/ubuntu/.docker/cli-plugins/docker-compose
  - chown -R ubuntu:ubuntu /home/ubuntu/.docker

  # NVM + Node LTS
  - su - ubuntu -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
  - su - ubuntu -c "export NVM_DIR=\"\$HOME/.nvm\" && . \"\$NVM_DIR/nvm.sh\" && nvm install --lts"

  # Oh My Zsh
  - su - ubuntu -c "sh -c \"\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""

  # Warp Terminal
  - WARP_DEB=$(curl -s https://api.warp.dev/latest/linux | grep -oP 'https://.*?\.deb')
  - wget "$WARP_DEB" -O warp.deb
  - apt install -y ./warp.deb
  - rm warp.deb

  # IBus Bamboo
  - add-apt-repository -y ppa:bamboo-engine/ibus-bamboo
  - apt update
  - apt install -y ibus-bamboo
  - ibus restart

  # Set Zsh as default
  - chsh -s /usr/bin/zsh ubuntu
